# Site
# repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: DO KYUNG KIM
title: Junior Web Developer & Studying NLP
email: kdky95@naver.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://kdkcode.github.io/dkFolio/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: kdkcode
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: dk_kdky95
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: channel/UCVSylrpUsoKaLzOApsYNfdg
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Academy Site
    icon: fa-light fa-sitemap
    # (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
    url: https://todaymathstudy.com/
    # - title: another link
    #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
    #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/dkprofile.jpg
about_content: |
  Hi, my name's Do Kyung KIM and I'm a junior web developer. As well as developing web, I am also good at communicating with people. I have worked at a number of companies gaining teamwork and leadership skills.
  I have also had the experience of independently managing a Smart Store. This experience has allowed me to gain valuable skills in business operations, customer service, and marketing strategies. 
  Through this opportunity, I further developed my communication, problem-solving, and decision-making abilities. It was a rewarding experience that enhanced my overall understanding of the e-commerce industry and provided me with valuable insights into running a successful online business.

  I am most skilled in: <mark>Python</mark> and <mark>Javascript</mark>

  # Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  # - Lists
  # - Tables
  # - <a href="google.com">Links</a>
  # - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Yogidam(여기담)
        link: https://yogidam.com/
        # (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/sovement/yogidam
            # (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title: Notion page for project (eg. sproogen/modern-resume-theme)
            icon: fa-regular fa-page
            url: https://www.notion.so/Sovement-e40b0c2d277941079993e1651461dc54
            # (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: |
          My first team project
        description: | # this will include new lines to allow paragraphs
          The platform aims to be a location service for smoking areas, with a focus on providing social value. 
          Our goal is to create a platform that helps smokers easily locate designated smoking areas, promoting responsible and considerate smoking practices. 
          By providing accurate and up-to-date information about smoking zones, we aim to enhance public awareness, reduce secondhand smoke exposure, and foster a more harmonious coexistence between smokers and non-smokers.
  
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: TodayMath
        link: https://todaymathstudy.com/
        link_text: math academy site
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/kdkcode/TodayMath
        quote: |
          Math Learning Center Website Built with React
        description: | # this will include new lines to allow paragraphs
          I have built a math learning center website using React and Node.js. 
          This project is a personal undertaking and is currently in progress.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: InfoSpread
        sub_title: Marketing
        caption: 2016 - 2022
        link: http://www.infospread.co.kr/
        quote: |
          Provide search advertising optimization services
        description: | # this will include new lines to allow paragraphs
          As a freelance marketer, I have conducted Naver search advertising and Google Analytics analysis for an English conversation company, 
          deriving insights and formulating advertising strategies.
  
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Yonsei University
        sub_title: BA Computer Science
        caption: 2020 - 2024
        quote: |
          Yonsei University is located in Sinchon, Seoul, South Korea.
        description: | # this will include new lines to allow paragraphs
          While attending university, I have a strong enthusiasm for acquiring new knowledge and gaining hands-on experience through various projects.
          With a future aspiration of starting my own startup, I have chosen to pursue a minor in Business Administration to complement my studies.
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I enjoy meeting new people and engaging in meaningful conversations. 
      In my free time, I am passionate about maintaining an active and healthy lifestyle through activities like fitness training and playing ice hockey.
      If you are interested in partnering for a startup, please feel free to reach out to me via email at kdky95@naver.com. 
      I am open to discussing potential entrepreneurial opportunities and exploring collaboration possibilities. I look forward to hearing from you.
      - Fitness Training
      - Ice Hockey
      - Startup
      - AI
      
# Footer
footer_show_references: true
